config/routes.rb
Rails.application.routes.draw do
  get 'macbeth/index'
  resources :xml_parses
  root 'macbeth#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/xml_parse.rb
class XmlParse < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/top_speakers.rb
module TopSpeakers

  extend ActiveSupport::Concern

  require 'nokogiri'
  require 'open-uri'
  require 'pp'

  def open_xml
    puts 'open_xml'
    @mac_file = open(@mac_url)
    @mac_html = @mac_file.read
    @mac_xml = Nokogiri::XML.parse(@mac_html) do |config|
      config.noblanks
    end
  end

  def make_speaker_hash
    puts 'make_speaker_hash'
    @speaker_line_count = Hash.new
    @mac_xml.css('SPEECH').each do |speech|
      @speaker_and_lines = speech.children
      speaker = @speaker_and_lines.first
      speaker_name = speaker.text
      # puts speaker_name
      # puts "in dict?: #{@speaker_line_count.key?(speaker_name)}"
      unless @speaker_line_count.key?(speaker_name)
        @speaker_line_count[speaker_name] = 0
        # puts "not in dict: #{@speaker_line_count[speaker_name]}"
      end
      # puts "in dict line count: #{@speaker_line_count[speaker_name]}"
      line_count = speech.xpath('./LINE').count
      # puts "adding line count: #{line_count}"
      @speaker_line_count[speaker_name] += line_count
      # puts "new line count: #{@speaker_line_count[speaker_name]}"
    end
    @speaker_line_count = @speaker_line_count.sort_by {|_key, value| value}.reverse
  end

  def parse_xml(mac_url)
    puts 'parse_xml'
    @mac_url = mac_url
    open_xml
    make_speaker_hash
  end

  def speaker_line_count
    return @speaker_line_count
  end

end

app/controllers/macbeth_controller.rb
class MacbethController < ApplicationController
  def index
  end


end

app/controllers/xml_parses_controller.rb
include TopSpeakers
class XmlParsesController < ApplicationController
	require 'pp'
	require 'nokogiri'
    require 'open-uri'

	def show
		@xml_parse = XmlParse.find(params[:id])

		parse_xml(@xml_parse.xml_url)
		@speaker_line_count
		pp @speaker_line_count
	end

	def new
	end

	def create
		@xml_parse = XmlParse.new(xml_parse_params)

		@xml_parse.save
		redirect_to @xml_parse
	end

	private
		def xml_parse_params
			params.require(:xml_parse).permit(:xml_url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/macbeth_helper.rb
module MacbethHelper
end

app/helpers/xml_parses_helper.rb
module XmlParsesHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MacbethApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/macbeth/index.html.erb
<h1>Enter the Macbeth xml url plz</h1>

<%= form_for :url do |f| %>
  <p>
    <%= f.label :xml_url %><br>
    <%= f.text_field :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/macbeth/xml_parses.html.erb
<h1>Enter the Macbeth xml url plz</h1>

<%= form_for :url do |f| %>
  <p>
    <%= f.label :xml_url %><br>
    <%= f.text_field :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/xml_parses/new.html.erb
<h1>Enter the Macbeth xml url plz</h1>

<%= form_for :xml_parse, url: xml_parses_path do |f| %>
  <p>
    <%= f.label :xml_url %><br>
    <%= f.text_field :xml_url %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/xml_parses/show.html.erb
<h1>Listing Top Speakers</h1>
 
<table>
  <tr>
    <th>Speaker</th>
    <th>Count</th>
  </tr>
 
  <% @speaker_line_count.each do |speaker_count| %>
    <tr>
      <td><%= speaker_count[0] %></td>
      <td><%= speaker_count[1] %></td>
    </tr>
  <% end %>
</table>
 